apiVersion: v1
kind: Config
clusters:
- cluster:
    server: http://mock-k8s:16443
    insecure-skip-tls-verify: true
  name: e2e-mock
contexts:
- context:
    cluster: e2e-mock
    user: e2e-user
  name: e2e-mock
current-context: e2e-mock
users:
- name: e2e-user
  user:
    token: e2e-mock-token-12345
