apiVersion: v1
kind: Secret
metadata:
  name: vaultwarden-sync-secrets
  namespace: vaultwarden-sync
  labels:
    app.kubernetes.io/name: vaultwarden-k8s-sync
    app.kubernetes.io/part-of: vaultwarden-sync
type: Opaque
stringData:
  # Vaultwarden sensitive configuration
  VAULTWARDEN__MASTERPASSWORD: "your-master-password"
  BW_CLIENTID: "your-client-id"
  BW_CLIENTSECRET: "your-client-secret"
  
  # Note: Replace the values above with your actual sensitive data
  # You can also use external secret management solutions like:
  # - External Secrets Operator
  # - Sealed Secrets
  # - HashiCorp Vault
  # - AWS Secrets Manager
  # - Azure Key Vault 
  # - Oracle Vault 