apiVersion: apps/v1
kind: Deployment
metadata:
  name: vaultwarden-sync
  namespace: vaultwarden-sync
  labels:
    app.kubernetes.io/name: vaultwarden-k8s-sync
    app.kubernetes.io/part-of: vaultwarden-sync
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: vaultwarden-k8s-sync
      app.kubernetes.io/part-of: vaultwarden-sync
  template:
    metadata:
      labels:
        app.kubernetes.io/name: vaultwarden-k8s-sync
        app.kubernetes.io/part-of: vaultwarden-sync
    spec:
      serviceAccountName: vaultwarden-sync
      containers:
        - name: vaultwarden-sync
          image: harbor.lag0.com.br/library/vaultwarden-k8s-sync:latest
          imagePullPolicy: Always
          command: ["dotnet", "VaultwardenK8sSync.dll", "sync"]
          envFrom:
            - configMapRef:
                name: vaultwarden-sync-config
                optional: true
            - secretRef:
                name: vaultwarden-sync-secrets
                optional: true
          resources:
            requests:
              memory: "128Mi"
              cpu: "10m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            exec:
              command:
                - dotnet
                - VaultwardenK8sSync.dll
                - config
            initialDelaySeconds: 30
            periodSeconds: 60
            timeoutSeconds: 10
            failureThreshold: 3
          readinessProbe:
            exec:
              command:
                - dotnet
                - VaultwardenK8sSync.dll
                - config
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
      restartPolicy: Always
      terminationGracePeriodSeconds: 30 