{{- if .Values.runAsCronJob }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "vaultwarden-k8s-sync.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "vaultwarden-k8s-sync.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  schedule: {{ .Values.schedule | quote }}
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 2
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app.kubernetes.io/name: {{ include "vaultwarden-k8s-sync.name" . }}
            app.kubernetes.io/instance: {{ .Release.Name }}
          annotations:
            {{- toYaml .Values.podAnnotations | nindent 12 }}
        spec:
          serviceAccountName: {{ include "vaultwarden-k8s-sync.serviceAccountName" . }}
          restartPolicy: OnFailure
          nodeSelector:
            {{- toYaml .Values.nodeSelector | nindent 12 }}
          tolerations:
            {{- toYaml .Values.tolerations | nindent 12 }}
          affinity:
            {{- toYaml .Values.affinity | nindent 12 }}
          containers:
            - name: {{ include "vaultwarden-k8s-sync.name" . }}
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              command: ["dotnet", "VaultwardenK8sSync.dll", "sync"]
              envFrom:
                - configMapRef:
                    name: {{ include "vaultwarden-k8s-sync.fullname" . }}-config
                    optional: true
              # Propagate SYNC__FIELD_* env overrides from values.env.fields
              {{- with .Values.env.fields }}
              env:
                - name: SYNC__FIELD__NAMESPACES
                  value: {{ .namespaces | quote }}
                - name: SYNC__FIELD__SECRETNAME
                  value: {{ .secretName | quote }}
                - name: SYNC__FIELD__SECRETKEYPASSWORD
                  value: {{ .secretKeyPassword | quote }}
                - name: SYNC__FIELD__SECRETKEYUSERNAME
                  value: {{ .secretKeyUsername | quote }}
                - name: SYNC__FIELD__SECRETKEY
                  value: {{ .secretKey | quote }}
                - name: SYNC__FIELD__INLINEKVPREFIX
                  value: {{ .inlineKvPrefix | quote }}
                - name: SYNC__FIELD__SECRETBLOCKPREFIX
                  value: {{ .secretBlockPrefix | quote }}
              {{- end }}
              env:
              {{- range $name, $ref := .Values.env.secrets }}
                - name: {{ $name }}
                  valueFrom:
                    secretKeyRef:
                      name: {{ $ref.secretName }}
                      key: {{ $ref.secretKey }}
                      optional: true
              {{- end }}
                # Force one-shot behavior under CronJob
                - name: SYNC__CONTINUOUSSYNC
                  value: "false"
              resources:
                {{- toYaml .Values.resources | nindent 16 }}
              securityContext:
                {{- toYaml .Values.securityContext | nindent 16 }}
{{- end }}
