apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "vaultwarden-k8s-sync.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "vaultwarden-k8s-sync.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "vaultwarden-k8s-sync.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        {{- toYaml .Values.podAnnotations | nindent 8 }}
      labels:
        app.kubernetes.io/name: {{ include "vaultwarden-k8s-sync.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ include "vaultwarden-k8s-sync.serviceAccountName" . }}
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
      affinity:
        {{- toYaml .Values.affinity | nindent 8 }}
      initContainers:
        - name: init-permissions
          image: busybox:1.36
          imagePullPolicy: IfNotPresent
          command: ["sh", "-c", "mkdir -p /data/home/.config && chown -R 1000:1000 /data /tmp"]
          securityContext:
            runAsUser: 0
          volumeMounts:
            - name: data
              mountPath: /data
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: data
          emptyDir: {}
        - name: tmp
          emptyDir: {}
      containers:
        - name: {{ include "vaultwarden-k8s-sync.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.debug }}
          command: ["tail", "-f", "/dev/null"]
          {{- else }}
          command: ["dotnet", "VaultwardenK8sSync.dll", "sync"]
          {{- end }}
          envFrom:
            - configMapRef:
                name: {{ include "vaultwarden-k8s-sync.fullname" . }}-config
                optional: true
          # Propagate SYNC__FIELD_* env overrides from values.env.fields
          {{- with .Values.env.fields }}
          env:
            - name: HOME
              value: "/data/home"
            - name: XDG_CONFIG_HOME
              value: "/data/home/.config"
            - name: SYNC__FIELD__NAMESPACES
              value: {{ .namespaces | quote }}
            - name: SYNC__FIELD__SECRETNAME
              value: {{ .secretName | quote }}
            - name: SYNC__FIELD__SECRETKEYPASSWORD
              value: {{ .secretKeyPassword | quote }}
            - name: SYNC__FIELD__SECRETKEYUSERNAME
              value: {{ .secretKeyUsername | quote }}
            - name: SYNC__FIELD__SECRETKEY
              value: {{ .secretKey | quote }}
            - name: SYNC__FIELD__INLINEKVPREFIX
              value: {{ .inlineKvPrefix | quote }}
            - name: SYNC__FIELD__SECRETBLOCKPREFIX
              value: {{ .secretBlockPrefix | quote }}
          {{- end }}
          {{- range $name, $ref := .Values.env.secrets }}
            - name: {{ $name }}
              valueFrom:
                secretKeyRef:
                  name: {{ $ref.secretName }}
                  key: {{ $ref.secretKey }}
                  optional: false
          {{- end }}
          volumeMounts:
            - name: data
              mountPath: /data
            - name: tmp
              mountPath: /tmp
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if not .Values.debug }}
          startupProbe:
            exec:
              command: ["sh", "-c", "test -f /proc/1/status"]
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 30
          livenessProbe:
            exec:
              command: ["sh", "-c", "test -f /proc/1/status"]
            periodSeconds: 60
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            exec:
              command: ["sh", "-c", "test -f /proc/1/status"]
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 2
          {{- end }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
