{{- if .Values.rbac.create }}
{{- if .Values.rbac.clusterWide }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "vaultwarden-k8s-sync.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "vaultwarden-k8s-sync.name" . }}
    app.kubernetes.io/part-of: {{ include "vaultwarden-k8s-sync.name" . }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "vaultwarden-k8s-sync.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "vaultwarden-k8s-sync.name" . }}
    app.kubernetes.io/part-of: {{ include "vaultwarden-k8s-sync.name" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "vaultwarden-k8s-sync.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "vaultwarden-k8s-sync.serviceAccountName" . }}
    {{- if .Values.namespace.create }}
    namespace: {{ .Values.namespace.name | quote }}
    {{- end }}
{{- else }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "vaultwarden-k8s-sync.fullname" . }}
  {{- if .Values.namespace.create }}
  namespace: {{ .Values.namespace.name | quote }}
  {{- end }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "vaultwarden-k8s-sync.fullname" . }}
  {{- if .Values.namespace.create }}
  namespace: {{ .Values.namespace.name | quote }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "vaultwarden-k8s-sync.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "vaultwarden-k8s-sync.serviceAccountName" . }}
    {{- if .Values.namespace.create }}
    namespace: {{ .Values.namespace.name | quote }}
    {{- end }}
{{- end }}
{{- end }}
