name: Pull Request Validation

on:
  pull_request:
    branches: [ main, develop ]

jobs:
  validate:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET 9.0.x
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore --configuration Release

    - name: Run tests
      run: dotnet test --no-build --verbosity normal --configuration Release

    - name: Check for TODO comments
      run: |
        if grep -r "TODO" VaultwardenK8sSync/ --include="*.cs"; then
          echo "Found TODO comments in source code"
          exit 1
        fi

    - name: Check for FIXME comments
      run: |
        if grep -r "FIXME" VaultwardenK8sSync/ --include="*.cs"; then
          echo "Found FIXME comments in source code"
          exit 1
        fi

    - name: Validate Helm chart
      run: |
        helm lint charts/vaultwarden-k8s-sync

    - name: Check Dockerfile
      run: |
        docker build --dry-run -f VaultwardenK8sSync/Dockerfile VaultwardenK8sSync/

  security:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET 9.0.x
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Check for vulnerable packages
      run: dotnet list package --vulnerable

    - name: Run dependency check
      run: dotnet restore --force-evaluate